# Generated by Django 4.0 on 2024-04-12 06:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e1999270-775b-48cc-98cd-989de35e6b13'), editable=False, primary_key=True, serialize=False)),
                ('difficulty', models.CharField(choices=[('ES', 'Easy'), ('MD', 'Medium'), ('HD', 'Hard'), ('EX', 'Extra')], default='MD', max_length=2)),
            ],
        ),
    ]
