# Generated by Django 4.0 on 2024-04-12 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b174a076-4ce6-4bfd-98ed-f2c558a55760'), editable=False, primary_key=True, serialize=False),
        ),
    ]
