# Generated by Django 4.0 on 2024-04-12 06:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_alter_exercise_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e2f6145d-8057-4663-8cd8-c8c95af56637'), editable=False, primary_key=True, serialize=False),
        ),
    ]
