# Generated by Django 4.0 on 2024-04-26 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_alter_exercise_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='chapter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='exercise.chapter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exercise.difficulty'),
        ),
    ]
