# Generated by Django 4.0 on 2024-04-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_chapter_difficulty_exercise_time_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(default='6 класс_pages-to-jpg-0107.jpg', upload_to='../res'),
            preserve_default=False,
        ),
    ]
